package ch14_exception;

public class TestMAin {
	public static void main(String[] args) {
		new ThrowEx ();	
		
	} 
	
}
